variable "filename"{
      default = "/root/terraform-1/terraform-variable/devops-automated.txt"
}
variable "filename1"{
      default = "/root/terraform-1/terraform-variable/devops-automated1.txt"
}

variable "content" {
     default = "This is the autogenerated file"
}


variable "dnyanu_cool" {}

variable "content_map" {
 type = map
 default = {
  "content-1"="This is my 1st coolest content for the tf file"
  "content-2"="This is my 2nd coolest content for the tf file"
}
}


variable "aws_ec2_object" {
   type = object ({
   name = string
   instances = number
   keys = list(string)
   ami = string
})
 default = {
   name = "aws_instance"
   instances = 5
   keys = ["key-1" , "key-2"]
   ami = "ami-asgttd122"
}
}
